# Generated by Django 4.2.2 on 2023-07-03 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0003_staff_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staff",
            old_name="date_of_admission",
            new_name="date_of_employment",
        ),
    ]
