# Generated by Django 4.2.2 on 2023-07-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0006_alter_staff_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="image",
            field=models.ImageField(blank=True, upload_to="staffs/images/"),
        ),
    ]
