# Generated by Django 4.2.2 on 2023-07-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0008_staff_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="user",
        ),
    ]
