# Generated by Django 4.2.2 on 2023-08-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0010_staff_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="role",
        ),
    ]
