# Generated by Django 4.2.2 on 2023-08-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0011_remove_staff_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="email",
            field=models.EmailField(blank=True, max_length=200),
        ),
    ]
