# Generated by Django 4.2.2 on 2023-06-20 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"ordering": ["student", "semester"]},
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="balance_from_previous_term",
            new_name="balance_from_previous_semester",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="term",
            new_name="semester",
        ),
    ]
