# Generated by Django 4.2.2 on 2023-07-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_student_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="user",
        ),
    ]
