# Generated by Django 4.2.2 on 2023-08-03 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0008_student_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": (["surname", "firstname", "other_name"],)},
        ),
    ]
