# Generated by Django 4.2.2 on 2023-08-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_alter_student_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="user",
        ),
    ]
