# Generated by Django 4.2.2 on 2023-08-10 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0013_alter_student_options_student_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="courses",
        ),
    ]
