# Generated by Django 4.2.2 on 2023-08-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0014_remove_student_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
