# Generated by Django 3.2.22 on 2024-06-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_student_created_at_student_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
