# Generated by Django 3.2.22 on 2024-06-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_student_is_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_enrolled',
            field=models.IntegerField(default=2024),
        ),
    ]
