# Generated by Django 3.2.22 on 2024-06-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_student_year_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_graduated',
            field=models.IntegerField(default=2024),
        ),
    ]
