# Generated by Django 3.2.22 on 2024-06-22 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0041_auto_20240621_1541'),
        ('students', '0020_alter_student_year_graduated'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.program'),
        ),
    ]
