# Generated by Django 4.2.2 on 2023-06-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("result", "0002_alter_result_options_rename_subject_result_course"),
        ("corecode", "0004_auto_20201124_0614"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subject",
            new_name="Course",
        ),
    ]
