# Generated by Django 4.2.2 on 2023-08-10 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0013_alter_student_options_student_user"),
        ("corecode", "0009_studentcourse_courseregistration"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentcourse",
            unique_together={("student", "course")},
        ),
        migrations.DeleteModel(
            name="CourseRegistration",
        ),
    ]
