# Generated by Django 4.2.2 on 2023-08-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0015_coursematerial_delete_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursematerial",
            name="type",
            field=models.CharField(
                choices=[
                    ("assignment", "Assignment"),
                    ("lecture_note", "Lecture Note"),
                    ("past_question", "Past Question"),
                    ("others", "Others"),
                ],
                default="assignment",
                max_length=20,
            ),
        ),
    ]
