# Generated by Django 4.2.2 on 2023-10-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0019_exam"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="course",
        ),
        migrations.AddField(
            model_name="exam",
            name="courses",
            field=models.ManyToManyField(to="corecode.course"),
        ),
    ]
