# Generated by Django 4.2.2 on 2023-10-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0020_remove_exam_course_exam_courses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="courses",
        ),
    ]
