# Generated by Django 3.2.22 on 2023-10-17 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0013_staff_created_at_staff_created_by_staff_updated_at_and_more'),
        ('corecode', '0023_academicsemester_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lecturer',
        ),
        migrations.AddField(
            model_name='course',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator', to='staffs.staff'),
        ),
    ]
