# Generated by Django 3.2.22 on 2024-06-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0030_auto_20240619_1255'),
    ]

    operations = [
    ]
