# Generated by Django 3.2.22 on 2024-06-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0032_auto_20240620_1356'),
    ]

    operations = [
       
    ]
