# Generated by Django 3.2.22 on 2024-06-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0033_alter_schedule_unique_together'),
    ]

    operations = [
      
    ]
