# Generated by Django 3.2.22 on 2024-06-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0035_auto_20240620_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('important_date', 'Important Dates and Deadlines'), ('holiday', 'Holidays and Breaks'), ('academic_event', 'Academic Events'), ('social_event', 'Social Events'), ('other_event', 'Other Events')], max_length=50),
        ),
    ]
